on: [push, pull_request]
name: Release to pypi
jobs:
  release-to-pypi:
    permissions:
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
    uses: deepmodeling/workflows/.github/workflows/release-to-pypi-id-token.yml@main
